#!/usr/bin/env sh

VALUE=3
TIME=200000

inc_brightness() {
	brillo -q -u $TIME -A $VALUE
	notify-send --replace-id=698 -i brightnesssettings -t 1800 "Brightness: $(brillo)%"
}
dec_brightness() {
	brillo -q -u $TIME -U $VALUE
	notify-send --replace-id=698 -i brightnesssettings -t 1800 "Brightness: $(brillo)%"
}

case "$1" in
"up") inc_brightness ;;
"down") dec_brightness ;;
*) echo "Woah! relax mate, this is how you use it:

\033[1;37mUsage: \033[0mlightctrl [COMMAND]

\033[1;37mCommands:\033[0m
  up                 increase the brightness by 10
  down               decrease the brightness by 10" ;;
esac

brillo -O
