#!/usr/bin/env bash

case "$1" in
--gimp) gimp ;;
--browser) $BROWSER ;;
--terminal) $TERMINAL ;;
--htop) $TERMINAL -e htop ;;
--editor) $TERMINAL -e nvim ;;
--filemanager) $TERMINAL -e lf ;;
--visualizer) $TERMINAL -c Cava -n Cava -e cava ;;
--music) $TERMINAL -c Ncmpcpp -n Ncmpcpp -e ncmpcpp ;;
--runner) rofi-runner ;;
--launcher) rofi-launcher ;;
--bookmarks) rofi-bookmarks ;;
--powermenu) rofi-powermenu ;;
--shortcuts) rofi-shortcuts ;;
--playermenu) rofi-playermenu ;;
*) echo "Don't know what to do?" ;;
esac
