#!/usr/bin/env bash

case "$1" in
--browser) apulse $BROWSER ;;
--terminal) $TERMINAL ;;
--anyterm) $TERMINAL -c AnyTerm -n AnyTerm ;;
--floatterm) $TERMINAL -c CustomFloat -n CustomFloat ;;
--editor) $TERMINAL -e nvim ;;
--filemanager) $TERMINAL -e lf ;;
--music) $TERMINAL -c Ncmpcpp -n Ncmpcpp -e ncmpcpp ;;
--runner) rofi-runner ;;
--launcher) rofi-launcher ;;
--bookmarks) rofi-bookmarks ;;
--powermenu) rofi-powermenu ;;
--shortcuts) rofi-shortcuts ;;
--passwords) rofi-passwords ;;
--playermenu) rofi-playermenu ;;
--wifi-toggle) rofi-wifi toggle;;
--vpn-toggle) $XDG_CONFIG_HOME/polybar/scripts/vpn toggle ;;
*) echo "Don't know what to do?" ;;
esac
