#!/bin/sh

[ -z "$1" ] && exit
base="$(basename "$1")"
notify-send "󰤄 Queuing $base..."
cmd="$2"
[ -z "$cmd" ] && cmd="yt-dlp --embed-metadata -ic"
idnum="$(ts $cmd "$1")"
realname="$(echo "$base" | sed "s/?\(source\|dest\).*//;s/%20/ /g")"
ts -D "$idnum" mv "$base" "$realname"
ts -D "$idnum" notify-send " $realname done."
