#!/usr/bin/env sh

program="$1"
[ "$program" = "st" ] && xrdb merge $HOME/.Xresources && pkill -USR1 $(pidof st) && exit 1
pkill -9 $program
$program &
notify-send -i reload -t 900 "$program" "Process restarted"
