#!/usr/bin/env bash

selected=$(virsh list --all --name | fzf)
[ -z "$selected" ] && exit 1

read -r -p "Press Enter to continue" </dev/tty

virsh destroy "$selected"
virsh undefine --domain "$selected" --wipe-storage --remove-all-storage --nvram
