#!/usr/bin/env bash

supports=$(egrep -c '(vmx|svm)' /proc/cpuinfo)

if [ $supports -eq 0 ]; then
	echo "[-] The CPU doesn't support virtualization."
	exit
fi

sudo xbps-install -Su libvirt virt-manager qemu polkit
sudo usermod -a -G libvirt,kvm dagregi $USER

cp -rv /etc/libvirt/libvirt.conf ~/.config/libvirt/
echo "uri_default = \"qemu:///system\"" >>~/.config/libvirt/libvirt.conf

sudo ln -s /etc/sv/dbus /var/service/
sudo ln -s /etc/sv/polkitd /var/service
sudo ln -s /etc/sv/libvirtd /var/service/
sudo ln -s /etc/sv/virtlockd /var/service/
sudo ln -s /etc/sv/virtlogd /var/service/

echo "[+] Setup complete."
