#!/usr/bin/env bash

supports=$(egrep -c '(vmx|svm)' /proc/cpuinfo)

if [ $supports -eq 0 ]; then
	echo "[-] The CPU doesn't support virtualization."
	exit
fi

sudo xbps-install -Suy libvirt virt-manager qemu polkit
sudo usermod -aG libvirt,kvm dagregi $USER

cp -rv /etc/libvirt/libvirt.conf ~/.config/libvirt/
echo "uri_default = \"qemu:///system\"" >>~/.config/libvirt/libvirt.conf

sudo ln -s /etc/sv/{dbus,virtlogd,virtlockd,libvirtd,polkitd} /var/service/

echo "[+] Setup complete."
