#!/usr/bin/env bash

music_dir="$HOME/Music"
previewdir="/tmp/previews"
filename="$(mpc --format "$music_dir"/%file% current)"
previewname="$previewdir/$(mpc --format %album% current | base64).png"

[ ! -d "$COVER_DIR" ] && mkdir -p $previewdir
[ -e "$previewname" ] || ffmpeg -y -i "$filename" -an -vf scale=80:80 "$previewname" >/dev/null 2>&1

notify-send -r 27072 "󰝚 $(mpc --format '%artist%' current)" "$(mpc --format '󰠃 %title%\n󰀥 %album%' current)" -i "$previewname"
