#!/usr/bin/env bash

folders="$(eval "echo \"$(cat "$BM_PROJECT")\"")"

[[ $# -eq 1 ]] && selected=$1 || selected=$(find $folders -mindepth 1 -maxdepth 1 -type d | sort -u | fzf)
[[ -z $selected ]] && exit 0
selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	tmux new-session -ds $selected_name -c $selected
else
	! tmux has-session -t=$selected_name 2>/dev/null && tmux new-session -ds $selected_name -c $selected
	tmux switch-client -t $selected_name
fi

tmux send-keys -t $selected_name:1 'nvim' C-m
tmux new-window -t $selected_name:2
tmux select-window -t $selected_name:1
tmux attach
