#!/usr/bin/env sh

time_out=1800
device=$(pactl list sinks | awk '/Name/ {print $2}')

get_volume() {
	pactl get-sink-volume "$device" | awk '{print $5}'
}

show_notification() {
	volume=$(get_volume | tr -d "%")
	if [ "$volume" -gt 75 ]; then
		icon="audio-volume-high"
	elif [ "$volume" -gt 35 ]; then
		icon="audio-volume-medium"
	else
		icon="audio-volume-low"
	fi
	dunstify -i "$icon" -t $time_out "Vol: $volume%"
}

adjust_volume() {
	operation="$1"
	is_muted=$(pactl get-sink-mute "$device" | awk '{print $2}')
	if [ "$is_muted" = "yes" ]; then
		pactl set-sink-mute "$device" false
	fi
	pactl set-sink-volume "$device" "$operation"
	show_notification
}

case "$1" in
"up") adjust_volume "+5%" ;;
"down") adjust_volume "-5%" ;;
"toggle")
	is_muted=$(pactl get-sink-mute "$device" | awk '{print $2}')
	if [ "$is_muted" = "yes" ]; then
		pactl set-sink-mute "$device" false
		show_notification
	else
		pactl set-sink-mute "$device" true
		dunstify -i audio-volume-muted -t $time_out "Muted"
	fi
	;;
*) echo "Woah! relax mate, this is how you use it:

\033[1;37mUsage: \033[0mvolumectrl [COMMAND]

\033[1;37mCommands:\033[0m
  up                 increase the volume by 5
  down               decrease the volume by 5
  toggle             toggle mute state" ;;
esac

polybar-msg action "#audio.hook.0"
