#!/usr/bin/env sh

time_out=1800

get_volume() {
	amixer -c 0 get Master | awk '/Mono/ {print $4}'
}

show_notification() {
	volume=$(get_volume | tr -d "\n\[\]%")
	if [ "$volume" -gt 75 ]; then
		icon="audio-volume-high"
	elif [ "$volume" -gt 35 ]; then
		icon="audio-volume-medium"
	else
		icon="audio-volume-low"
	fi
	notify-send --replace-id=698 -i "$icon" -t $time_out "Vol: $volume%"
}

adjust_volume() {
	operation="$1"
	is_muted=$(amixer -c 0 get Master | awk '/Mono/ {print $6}' | tr -d "\n\[\]")
	if [ "$is_muted" = "off" ]; then
		amixer -c 0 set Master unmute
	fi
	amixer -c 0 set Master "$operation"
	show_notification
}

case "$1" in
"up") adjust_volume "5%+" ;;
"down") adjust_volume "5%-" ;;
"toggle")
	is_muted=$(amixer -c 0 get Master | awk '/Mono/ {print $6}' | tr -d "\n\[\]")
	if [ "$is_muted" = "off" ]; then
		amixer -c 0 set Master unmute
		show_notification
	else
		amixer -c 0 set Master mute
		notify-send --replace-id=698 -i audio-volume-muted -t $time_out "Muted"
	fi
	;;
*) echo "Woah! relax mate, this is how you use it:

\033[1;37mUsage: \033[0mvolumectrl [COMMAND]

\033[1;37mCommands:\033[0m
  up                 increase the volume by 5
  down               decrease the volume by 5
  toggle             toggle mute state" ;;
esac

# polybar-msg action "#audio.hook.0"
