#!/usr/bin/env bash

pass_folders=${PASSWORD_STORE_DIR-~/.password-store}
pass_files=$(find "$pass_folders" -name '*.gpg' -type f -printf '%P\n' | sed 's/\.gpg$//' | sort)

password=$(echo "$pass_files" | rofi -dmenu -theme $XDG_CONFIG_HOME/rofi/themes/bookmarks.rasi)
[[ -n $password ]] || exit

pass show -c "$password"
