#!/usr/bin/env bash

COVER_PATH="/tmp/previews"
time_out=1800
status=$(mpc status)
artist=$(mpc current -f %artist%)
title=$(mpc current -f %title%)
album=$(mpc current -f %album%)
is_stopped=$(awk '{ print $2 }' <<<"$status")
is_repeat=$(awk '/repeat/ { print $3 }' <<<"$status")
is_shuffle=$(awk '/random/ { print $5 }' <<<"$status")
is_playing=$(awk '/\[/ { print $1 }' <<<"$status" | tr -d '\[\]')

check_status() {
	[ -z "$status" ] && prompt="Offline" && message="MPD is Offline"
	[ "$is_stopped" = "n/a" ] && prompt="Stopped" && message="Playback stopped"
	[ -n "$status" ] && [ "$is_stopped" != "n/a" ] && prompt="$artist" && message="󰝚  $title
󰀥  $album"
}

update_cover() {
	if [ ! -e "$1-raw.png" ]; then
		ffmpeg -y -i "$HOME/Music/$(mpc current -f %file%)" -an -vf scale=360:360 "$1-raw.png" >/dev/null 2>&1
	fi
	cover="$1-raw.png"
}

toggle_play_pause() {
	[ -n "$status" ] && mpc -q toggle && dunstify --replace=696 -t $time_out "$(mpc status | awk '/\[/ { print $1 }' | tr -d '\[\]' | sed 's/p/P/')" || exit 0
}
stop_playback() {
	mpc -q stop
	dunstify --replace=696 -i media-playback-stop -t $time_out "Playback stopped"
}

toggle_shuffle() {
	[ -n "$status" ] && mpc -q random && dunstify --replace=696 -i media-playlist-shuffle -t $time_out "Random: $(mpc status | awk '/random/ { print $5 }')" || exit 0
}
toggle_repeat() {
	[ -n "$status" ] && mpc -q repeat && dunstify --replace=696 -i media-playlist-repeat -t $time_out "Repeat: $(mpc status | awk '/repeat/ { print $3 }')" || exit 0
}

next_track() {
	[ "$is_stopped" != "n/a" ] && [ -n "$status" ] && mpc -q next && songchanged || exit 0
}
prev_track() {
	[ "$is_stopped" != "n/a" ] && [ -n "$status" ] && mpc -q prev && songchanged || exit 0
}

update_options() {
	[ "$is_playing" = "playing" ] && toggle_opt="󰏤" || toggle_opt="󰐊"
	prev_opt="󰒮"
	next_opt="󰒭"
	stop_opt="󰓛"
	shuffle_opt="󰒝"
	repeat_opt="󰑖"
	urgent=""
	[ "$is_repeat" = "off" ] && [ "$is_shuffle" = "off" ] && active=""
	[ "$is_repeat" = "on" ] && [ "$is_shuffle" = "off" ] && active="4"
	[ "$is_repeat" = "off" ] && [ "$is_shuffle" = "on" ] && active="5"
	[ "$is_repeat" = "on" ] && [ "$is_shuffle" = "on" ] && active="4,5"
	[ "$is_stopped" = "n/a" ] && urgent="3"
}

main() {
	check_status
	update_options
	update_cover "$COVER_PATH/$album"
	state=$(
		echo -e "$prev_opt\n$toggle_opt\n$next_opt\n$stop_opt\n$repeat_opt\n$shuffle_opt" |
			rofi -dmenu \
				-selected-row 1 \
				-theme-str "inputbar {background-image: url(\"$cover\", width);}" \
				-p "$prompt" \
				-mesg "$message" \
				-a "${active}" -u "$urgent" \
				-theme "$XDG_CONFIG_HOME/rofi/themes/playermenu.rasi"
	)

	case "$state" in
	"$toggle_opt") toggle_play_pause ;;
	"$stop_opt") stop_playback ;;
	"$next_opt") next_track ;;
	"$prev_opt") prev_track ;;
	"$repeat_opt") toggle_repeat ;;
	"$shuffle_opt") toggle_shuffle ;;
	*) echo "Don't know what to do" ;;
	esac
}

main
