#!/usr/bin/env bash

awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}' ~/.config/sxhkd/sxhkdrc |
	column -t -s $'\t' | rofi -dmenu -markup-rows -theme $XDG_CONFIG_HOME/rofi/themes/sxhkd.rasi
