#!/usr/bin/env bash

shutdown_opt="󰐥"
logoff_opt="󰍃"
restart_opt="󰜉"
lock_opt=""
lock_screen() {
	[ -n "$(mpc status)" ] && mpc -q pause
	slock
}
logoff() {
	mpd --kill
	bspc quit
}
state=$(echo -e "$lock_opt\n$logoff_opt\n$restart_opt\n$shutdown_opt" | rofi -dmenu -u -1 -theme $XDG_CONFIG_HOME/rofi/themes/powermenu.rasi)
[ -n "$state" ] && confirmation=$(echo -e "Yes\nNo" | rofi-confirm)

[ "$confirmation" = "Yes" ] && case "$state" in
"$shutdown_opt") sudo -A poweroff ;;
"$restart_opt") sudo -A reboot ;;
"$lock_opt") lock_screen ;;
"$logoff_opt") logoff ;;
*) echo "Stil don't know what to do!" ;;
esac || exit 0
